sudo: required

language: ruby

services:
  - docker

rvm:
  - 2.3.1

script: bundle exec rspec spec

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    docker build -t dpca/slack-fooda-bot .
    docker push dpca/slack-fooda-bot
    fi
