sudo: required

language: ruby

cache: bundler

services:
  - docker

rvm:
  - 2.5

addons:
  code_climate:
    repo_token: d71e4c1efd740edfac8693d04042ae291a3692b9e2ddc032257cca41fd3c6358

script: bundle exec rspec spec

after_success:
  - bundle exec codeclimate-test-reporter
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker build -t dpca/slack-fooda-bot .;
    docker push dpca/slack-fooda-bot;
    fi
