version: '2'
services:
  redis:
    image: redis
    volumes:
      - ./data:/data

  foodabot:
    build: .
    links:
      - redis
    env_file: .env
    environment:
      REDIS_URL: redis://redis
